hydra:
  run:
    dir: byog/runs/${oc.env:SLURM_JOB_ID}

defaults:
  - config_base
  - _self_

dataset:
  max_size_labeled: null
  max_size_unlabed: null
  debug_mode: false

encoder_llm_name: "EleutherAI/pythia-160m"
predictor_llm_name: "EleutherAI/pythia-160m"
encoder_llm_trainable: true
predictor_llm_trainable: true

encoder_lr: 1e-5
predictor_lr: 5e-5
weight_decay: 0.05
batch_size: 16
epochs: 6

checkpoint_best_key: "valid/loss_labeled.data"
