hydra:
  run:
    dir: byog/runs/${oc.env:SLURM_JOB_ID}

defaults:
  - config_base
  - _self_

dataset:
  max_size_labeled: 20_000
  max_size_unlabed: 100_000
  debug_mode: false

lr: 2e-5
batch_size: 16
