hydra:
  run:
    dir: byog/runs/${oc.env:SLURM_JOB_ID}

defaults:
  - config_base
  - _self_

encoder_llm_name: "EleutherAI/pythia-160m"
predictor_llm_name: "EleutherAI/pythia-160m"
encoder_llm_trainable: true
predictor_llm_trainable: true

valid_size: 0.01

encoder_lr: 1e-5
predictor_lr: 5e-5
weight_decay: 0.1
batch_size: 16
epochs: 5

checkpoint_best_key: null
